spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm?serverTimezone=UTC
    username: root
    password: 2784247628
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/static/




  mvc:
    static-path-pattern: /static/**

mybatis:
  mapper-locations: classpath:/mappers/*.xml
